### ISSUE TITLE
[ENH] uv package manager

### ISSUE THREAD

**Issue by matteoettam09** [skfolio/skfolio#104]
**Is your feature request related to a problem? Please describe.**

Better package manager.

**Describe the solution you'd like**
https://dev.to/astrojuanlu/python-packaging-is-great-now-uv-is-all-you-need-4i2d

**Describe alternatives you've considered**

pip, conda, poetry.
uv wins.

**Comment by CarloNicolini** [comment]
Totally agree. Already at the moment if you simply clone skfolio locally and run one of the examples, everything works fine. The code is run and a plot appears in the browser.

```bash
uv venv
uv run python examples/mean_risk/plot_1_maximum_sharpe_ratio.py
```

**Comment by HugoDelatte** [comment]
`uv` seems indeed superior to existing tools.

The downside is that it is still quite new, so not all users will be familiar with it and Skfolio has only 7 dependencies making the existing config (pip / pyproject.toml) quite robust. That was also the reason I didn't initially use poetry even tho I'm a big poetry user for my persol projects (which have much more dependencies).

I don't know `uv` as much as you do so maybe I'm missing smth: is there a clear benefit of using it for packages with few dependencies like Skfolio?

**Comment by matteoettam09** [comment]
If anything, it's faster. Check the commit I have just done on the issue. In this way only the cicd and users using make will be exposed to uv, while the toml of the project is still agnostic to that.
