### ISSUE TITLE
[BUG] Annualization factor with 252 business days in a year

### ISSUE THREAD

**Issue by CarloNicolini** [skfolio/skfolio#11]
**Describe the bug**
In all metrics the 255 business days standard is used.
On average US based calendar has 252 business days in a year.
While I understand this depends on the country and on the specific year, most annualization metrics should at least be clear about it.

**Expected behavior**
Annualization should be based on typically 252 business days for US based user.

**Comment by HugoDelatte** [comment]
Correct, it should be 252 indeed

**Comment by HugoDelatte** [comment]
I'm working on this
