### ISSUE TITLE
[DOC] how to customize datasets？

### ISSUE THREAD

**Issue by leegang** [skfolio/skfolio#12]
### Describe the issue linked to the documentation
https://skfolio.org/user_guide/datasets.html
The user is requesting the addition of documentation on how to customize datasets. Currently, the native datasets provided only include a portion of stocks from the S&P 500 and NASDAQ. In order to construct a portfolio of ETFs or stocks from other countries' markets, there is a need for custom datasets.

### Suggest a potential alternative/fix
Provide information on how to create and customize datasets, ideally with relevant code examples.

**Comment by CarloNicolini** [comment]
I believe datasets should be kept outside of the project. The examples here are really examples.
Tools like yahoo finance makes it possible to download spot prices for a number of instruments, securities, etf, etcetera.
We could create a small example on getting adjusted close data from yahoo finance but it would not really be related to the main goal of skfolio, rather it is something more related to pandas data wrangling.
Tell me if I got your point correctly.

**Comment by leegang** [comment]
> I believe datasets should be kept outside of the project. The examples here are really examples. Tools like yahoo finance makes it possible to download spot prices for a number of instruments, securities, etf, etcetera. We could create a small example on getting adjusted close data from yahoo finance but it would not really be related to the main goal of skfolio, rather it is something more related to pandas data wrangling. Tell me if I got your point correctly.

Is it sufficient for the dataset to be a pandas DataFrame as long as it has dates as the index and securities as columns? Should the prices be adjusted or unadjusted?

**Comment by CarloNicolini** [comment]
If prices are not adjusted you risk introducing incorrect returns calculation, with possible large swings in case for example dividends or stock splits have not been taken into account.
I suggest using adjusted close prices for computing asset returns.

**Comment by leegang** [comment]
Got it.
