### ISSUE TITLE
[DOC] jupyerlite kernel & notebooks paths

### ISSUE THREAD

**Issue by treatmesubj** [skfolio/skfolio#2]
#### Describe the issue linked to the documentation

Wow, super cool library & docs.
I had not seen [sphinx-gallery](https://sphinx-gallery.github.io/) docs before, they look nice. It looks like the [gallery](https://sphinx-gallery.github.io/stable/auto_examples/index.html) includes a jupyterlite environment where you can run notebooks [like this](https://sphinx-gallery.github.io/stable/lite/lab/); I haven't seen that before either. 

#### Suggest a potential alternative/fix

Given the docs are hosted on GitHub pages for now, I guess you probably can't [install and run a kernel](https://jupyterlite.readthedocs.io/en/latest/howto/pyodide/pyodide.html) in that environment. It seemed that it couldn't quite find the notebooks, for example, `https://skfolio.org/lite/lab/?path=auto_examples/1_mean_risk/plot_1_maximum_sharpe_ratio.ipynb`, but maybe that can be fixed in [conf.py](https://github.com/skfolio/skfolio/blob/v0.0.8/docs/conf.py) via [these docs](https://jupyterlite-sphinx.readthedocs.io/en/latest/configuration.html) - maybe the notebook can still be displayed nicely in jupyterlite, just not run, which would probably still be cool. 
Either way, maybe you'd want to temporarily remove allusions to the jupyterlite pages from your docs, e.g. [plot_1_maximum_sharpe_ratio.html#L399](https://github.com/skfolio/skfolio/blob/gh-pages/auto_examples/1_mean_risk/plot_1_maximum_sharpe_ratio.html#L399) & [plot_1_maximum_sharpe_ratio.html#L836](https://github.com/skfolio/skfolio/blob/gh-pages/auto_examples/1_mean_risk/plot_1_maximum_sharpe_ratio.html#L836) with a script or something, or maybe can just be done in sphinx-gallery build.

**Comment by HugoDelatte** [comment]
Thank you very much!
Very good spot, the folder "files" containing the notbooks is missing from https://github.com/skfolio/skfolio/tree/gh-pages/lite
I'll investigate why the GitHub workflow didn't generate it.

**Comment by HugoDelatte** [comment]
The jupyterlite configuration was missing in conf.py under sphinx_gallery_conf. However, after more testing, the first import was too slow as described here: https://sphinx-gallery.github.io/stable/configuration.html#generate-jupyterlite-links-for-gallery-notebooks-experimental
So I replaced jupyterlite by binder.
Fixed in https://github.com/skfolio/skfolio/releases/v0.0.9

**Comment by treatmesubj** [comment]
Works. Wow, Binder is [cool tech](https://binderhub.readthedocs.io/en/latest/overview.html). Crazy they build images & run K8s cluster of pods/containers w/ 4GB RAM each & just execute arbitrary code in notebooks from the internet for free! From this [white paper](https://zenodo.org/records/7362188), it sounds like the German government pays for it through the [GRF](https://en.wikipedia.org/wiki/German_Research_Foundation). Cool

**Comment by HugoDelatte** [comment]
Indeed, what they offer is quite amazing. They give more details about resources [here](https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html#resources-available)
Didn't know GRF was a sponsor, very interesting!
