### ISSUE TITLE
[BUG] Population.plot_cumulative_returns() does not show all portfolios

### ISSUE THREAD

**Issue by SebasPelaez** [skfolio/skfolio#38]
**Describe the bug**

When integrating 2 portfolios into the `Population` class that result from an `MeanRisk()` with a third portfolio that was created with the `Portfolio` class, when I try to use the `plot_cumulative_returns()` method, only 1 portfolio is shown.

**To Reproduce**

```python
X = pd.DataFrame(np.random.rand(365,3), columns=["SPY", "GOVT", "QQQ"], 
                 index=pd.date_range(start='2018-01-01', end='2018-12-31'))

model = MeanRisk(
    risk_measure=RiskMeasure.VARIANCE,
    objective_function=ObjectiveFunction.MAXIMIZE_RATIO,
    portfolio_params=dict(name="Max Sharpe"),
    min_weights={"SPY": 0.3, "GOVT": 0.1},
    max_weights={"SPY": 0.30001, "GOVT": 0.10001}
)

benchmark_inv = InverseVolatility(portfolio_params=dict(name="Inverse Vol"))
benchmark = Portfolio(X["SPY"].to_numpy().reshape(-1, 1), weights=[1.0], name="OnlySPY")

benchmark_inv.fit(X)
model.fit(X)

pred_model = model.predict(X)
pred_bench = benchmark_inv.predict(X)

fig = Population([pred_model, benchmark, pred_bench]).plot_cumulative_returns()
show(fig)
```

**Expected behavior**

The image should show the three portfolio cumulative returns.

**Versions**
```
import skfolio; print(skfolio.__version__)
0.1.2
```

**Comment by HugoDelatte** [comment]
To sort this, you need to create your benchmark with:
```python
benchmark = Portfolio(X[["SPY"]], weights=[1.0], name="OnlySPY")
```

as opposed to:
```python
benchmark = Portfolio(X["SPY"].to_numpy().reshape(-1, 1), weights=[1.0], name="OnlySPY")
```

This is because your input X has a datetime index, and by converting is to a numpy you lose that index which create an error when you try to use both in a `Population`. However, we should detect it and throw an explicit error --> I'll create a PR.

**Comment by SebasPelaez** [comment]
You are absolutely right, I made this change and the expected behavior occurred. Thank you so much.
