### ISSUE TITLE
[DOC] Type Hints Suggestion.

### ISSUE THREAD

**Issue by vacarme** [skfolio/skfolio#40]
#### Describe the issue linked to the documentation
Let's see type hints as documentation for the IDE :)

Let me suggest some improvements to some type hints encountered throughout the code.

I will upload this issue alongside my PR.

The goal of this issue is not to discuss design choices and their implications on the hints but to help with minor suggestions.  

Type issues:
+ used of `any` the python built-on instead of `Any` the type.

**Comment by HugoDelatte** [comment]
Thank you, looking forward for your PR

**Comment by vacarme** [comment]
sorry as a matter of fact I am quite busy for now. 

To close this issue I submitted a PR with a fix for the main misused type hints: `any` instead of `Any`.

Very short to read.
