### ISSUE TITLE
Differently Sized Series

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#67]
Securities often have different lenghts, how would you deal with this? Thanks for the package.

**Comment by HugoDelatte** [comment]
Hello, the solution would be to implement Transformers. It's in our roadmap. For more details, it's related to [this discussion](https://github.com/skfolio/skfolio/discussions/60).

**Comment by firmai** [comment]
Happy to see it is the good type of transformer **pandas.DataFrame.transform**. Do you want me to implement it, I can look at it on Monday, or have you already started?

**Comment by HugoDelatte** [comment]
Thank you for proposing to implement it. 

The work has already started: I'll push it in a feature branch soon so you can participate in its development. 

I'm referring to the `Transformer` class of scikit-learn. In `skfolio`, transformers are currently used in asset pre-selection. You can see the user guide [here](https://skfolio.org/user_guide/pre_selection.html) and examples [here](https://skfolio.org/auto_examples/7_pre_selection/index.html)

The solution is to implement `Transformer` and `Imputer` as described [here](https://github.com/skfolio/skfolio/discussions/60#discussioncomment-9720472).

Asset time series have different sizes for various reasons (e.g., stock defaulted, stock inception, bond expired). Some reasons are deterministic (e.g., bond expiry), and some are not (e.g., stock default). Therefore, the way you drop assets and impute missing values will differ to avoid data leakage and optimize the available information.

Could you kindly explain your use case (why your data has different sizes) to see if it fits with what I described above?

**Comment by firmai** [comment]
I think the marjority of use-cases for me would be stock inception and delistings. Excellent, I will keep my eye out for the branch.

**Comment by firmai** [comment]
Is there a possibility to make `skfolio.exceptions.NonPositiveVarianceError: The following assets have a non positive variance: ['SACH-PA', 'PLNR', 'LMOS', 'MCELQ', 'CYT1', 'MTWVQ', 'SPA', 'EAGL2', 'TRC.R', 'TNCC', 'CSUNY', 'CYTXW', 'SONC', 'TRVS', 'STS', 'BFAC.WS', 'AWIN1', 'TONEQ', 'STI.WSB', 'PPYAW', 'BZET', 'DRAY', 'IN', 'CIV.A', 'AITRR', 'TROV1', 'CCSI1', 'FTRL', 'NEWS', 'ALORU', 'COCOQ', 'CCG', 'MEKA']` less restrictive so that we force it to work even if some optimization step complains later on.

**Comment by HugoDelatte** [comment]
Yes if you fill with a constant value, you get zero variance. In that case, that asset should be removed before the optimization instead.
We could set it as a warning, but the optimization step will fail anyway so it won't help much. It's a problem that should be handled at the previous step, by using either pre-processing or Transformers and Imputers https://github.com/skfolio/skfolio/issues/67#issuecomment-2241550345
