### ISSUE TITLE
Date Matched Composition

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#69]
With multiperiod walk-forward portfolio, we are able to grab the compositions over the multiple rebalancing periods. It would be great to have a date-matched composition i.e., portfolio weights, even if the weights repeat for multiple days, I can think of a dataframe days x assets, and then of course the NaN return dates will have zero weight for the respective asset. I have around 5 more suggestions to make, I will open a new issue for each. This is what the composition looks like currently.

![image](https://github.com/user-attachments/assets/5c6c6f77-faff-4eec-88a8-8238bf2ad0fd)

maybe `.portfolio_weights`, `.daily_weights` something like that could distinguish from above.

**Comment by firmai** [comment]
I think it is better not to do it as a post-processing step due to countless errors that could creep up, however here is the post-processing code that I am currently working with.

```
import pandas as pd
import numpy as np
from datetime import timedelta

def create_daily_weights(df_select, model_composition, train_size=252, test_size=90):
    # Create a DataFrame with the same index and columns as df_select
    daily_weights = pd.DataFrame(index=df_select.index, columns=df_select.columns, dtype=float)
    
    # Calculate the start date for the first prediction
    start_date = df_select.index[train_size]
    
    # Generate rebalancing dates
    rebalancing_dates = [start_date]
    current_date = start_date
    while current_date < df_select.index[-1]:
        current_date += timedelta(days=test_size)
        if current_date <= df_select.index[-1]:
            rebalancing_dates.append(current_date)
    
    # Determine the number of periods to iterate over
    n_periods = min(len(rebalancing_dates), model_composition.shape[1])
    
    # Iterate through the rebalancing dates
    for i in range(n_periods):
        rebalance_date = rebalancing_dates[i]
        # Get weights for this period
        weights = model_composition.iloc[:, i]
        
        # Determine end date for this period
        if i == n_periods - 1:
            end_date = df_select.index[-1]
        else:
            end_date = rebalancing_dates[i+1] - timedelta(days=1)
        
        # Align the weights with df_select columns
        aligned_weights = weights.reindex(df_select.columns, fill_value=0)
        
        # Fill the weights for this period
        daily_weights.loc[rebalance_date:end_date] = aligned_weights.values
    
    # Forward fill any remaining NaN values
    daily_weights = daily_weights.ffill()
    
    # Ensure we only have weights for dates after the first prediction date
    daily_weights = daily_weights.loc[start_date:]
    
    return daily_weights

# Usage
# Assuming df_select and summary_dict["HRP"].composition are already defined
model_composition = summary_dict["HRP"].composition

## Same as CV
daily_weights = create_daily_weights(df_select, model_composition, train_size=252, test_size=90)

```
![image](https://github.com/user-attachments/assets/bd12018d-c0a1-4c61-a9c7-409d12268d37)

**Comment by HugoDelatte** [comment]
Yes could be useful, where do you think it could live? As a `Portfolio` method?

**Comment by firmai** [comment]
That would make the most sense yeah. Also haven't congragulated you on the package, its excellent. I am looking forward to seeing it evolve. I won't have much time to help from next week onwards due to the summer semester, but if any of my open issues are undone by September, I will take care of them.

**Comment by HugoDelatte** [comment]
Thank you very much. Noted, I'll start working on them.

**Comment by HugoDelatte** [comment]
Implementation done in dev branch here:

https://github.com/skfolio/skfolio/blob/d0d3b33f5ca3e27e45ac525c788ead119c83e92c/src/skfolio/portfolio/_portfolio.py#L670

https://github.com/skfolio/skfolio/blob/d0d3b33f5ca3e27e45ac525c788ead119c83e92c/src/skfolio/portfolio/_multi_period_portfolio.py#L560
