### ISSUE TITLE
Rolling Measure for Population

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#70]
Currently the rolling measure plot only works for portfolios and not for populations. This could be a helpful addition. Expected behaviour. 

```
population.plot_rolling_measure(measure=RatioMeasure.SHARPE_RATIO)
```

Then if 4 difference portfolios in population, they would all be plotted

**Comment by HugoDelatte** [comment]
Yes agreed, good idea. Do you wish to create a PR for it otherwise I can do it?

**Comment by HugoDelatte** [comment]
Implementation done in dev branch here:
https://github.com/skfolio/skfolio/blob/128f619960494f827fb2205e1a9d5cca383092d8/src/skfolio/population/_population.py#L455
