### ISSUE TITLE
Date-centered Test Sets (Rebalancing)

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#71]
As of now, the CV is valuable, but to bring it closer to asset management as opposed to data science the rebalancing ordinarily doesn't occur in a number of days, but perhaps on the 15th of every month or every 4th Friday. 

Expected behaviour: 

```

##polars nomenclature
self.cv = WalkForwardDate(period=252, every="4w",  offset="-3d") ## This would run every 4th Friday.

##asset management nomenclature
self.cv = WalkForwardDate(lookback=252, rebalance="4w",  offset="-3d") ## This would run every 4th Friday.
```

Here I am taking inspiration from the `group_by_dynamic` from polars.

```
    df_signal_long.group_by_dynamic(
                index_column=date_col,
                every=every,
                period=f"{lookback}{every[-1]}" if isinstance(lookback, int) else lookback,
                by=entity_col,
                closed="left",
                label="left",
                offset="-3d",  # Offset by 3 days to end on Friday
                include_boundaries=False
            )
```

**Comment by HugoDelatte** [comment]
Yes also a good idea. It's related to https://github.com/skfolio/skfolio/discussions/41#discussioncomment-8889409
I'll list all arguments and features that I have in mind taking inspiration from that previous discussion and the polar implementation you mentioned
